### ISSUE TITLE
Update integration step image

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/test-infra#303]
Currently the integration step fails to compile given test because it contains go@1.13 features - ref https://concourse.ci.gardener.cloud/teams/gardener/pipelines/test-infra-master/jobs/master-head-update-job/builds/6.

Currently the used image is `eu.gcr.io/gardener-project/cc/job-image-golang:0.10.0`
```
$ docker run eu.gcr.io/gardener-project/cc/job-image-golang:0.10.0 go version
go version go1.12.6 linux/amd64
```

The image needs to be updated to `eu.gcr.io/gardener-project/cc/job-image-golang:0.12.0`

```
$ docker run eu.gcr.io/gardener-project/cc/job-image-golang:0.12.0 go version
go version go1.13.9 linux/amd64
```

PS: I am opening an issue as I don't have rights to push to `refs/meta/ci` or create a PR about it :(

**Comment by ialidzhikov** [comment]
@schrodit , @dguendisch could you please assist? It should be 1 minute change.

/assign @schrodit @dguendisch

**Comment by dguendisch** [comment]
Thanks a lot for pointing out! Fixed with https://github.com/gardener/test-infra/commit/391c4bd6c3d3d766e27bb62a63a699f27018477e
(did I say that I _hate_ `refs/meta/ci`? 👻)
