### ISSUE TITLE
Support selecting the network type calico<->cilium

### ISSUE THREAD

**Issue by dguendisch** [gardener/test-infra#377]
Testmachinery should support switching the [network type via the shoot spec](https://github.com/gardener/gardener/blob/master/example/90-shoot.yaml#L287) to allow tests to be created that don't target the default (calico) but can target cilium as well.
- [ ] Testmachinery flavors need to support this
- [x] [CreateShoot step](https://github.com/gardener/gardener/blob/master/.test-defs/CreateShoot.yaml) in g/g needs to support this

**Comment by hendrikKahl** [comment]
https://github.com/gardener/gardener/pull/5257 introduces the `NETWORKING_TYPE` parameter to the `CreateShoot` test definition. The framework is already capable of specifying the network type.
