### ISSUE TITLE
replace "component-spec" language bindings w/ OCM-Lib

### ISSUE THREAD

**Issue by ccwienk** [gardener/test-infra#457]
# Context / Motivation

[component-cli](https://github.com/gardener/component-cli) was deprecated (superseded by [ocm-cli](https://github.com/open-component-model/ocm) and removed from gardener-cicd (pipeline template and all pipelines) as part of [cleanup and consolidation](https://github.tools.sap/kubernetes/cicd-backlog/issues/1) activity.

`component-cli` as well as testmachinery uses golang bindings from [component-spec](https://github.com/gardener/component-spec) repository for retrieving and deserialising OCM-Component-Descriptors. Said language-bindings were also superseded by a re-implementation (in golang) in [ocm-repository](https://github.com/open-component-model/ocm).

The re-implemented ocm-lib supports handling of different versions of component-descriptors w/ a stable API (which is promised to be kept stable also for future spec-versions of OCM; there are already two spec-versions: v2 and v3 (gardener-cicd currently uses v2).

Adopting the re-implemented ocm-lib in testmachinery will allow us to archive the (currently unmaintained) "component-spec"-language-bindings and (hopefully) reduce related maintenance efforts in the future.

# Implementation Proposal

Remove dependencies from testmachinery towards https://github.com/gardener/component-spec, and port it to using [ocm-lib](https://github.com/open-component-model/ocm) instead.

**Comment by ccwienk** [comment]
@dguendisch | @hendrikKahl : @fabianburth might help you w/ this task

**Comment by fabianburth** [comment]
Just wanted to mention that I did not forget about this but had a shift of priorities. I will try to get to this soon!
